.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH tuxcast-config 1 "MAY 2006" 0.1 "tuxcast 0.1"
.SH NAME
tuxcast-config \- tuxcast configuration utility
.SH SYNOPSIS
.B tuxcast-config [option] name
.SH DESCRIPTION
A configuration utility for Tuxcast. It must be run before the
main tuxcast program can be run. It generates the required XML
configuration files to define feeds and destination directories.

Its configuration is performed by the included
.B tuxcast-config 
utility which must be
run to configure feeds and generate tuxcast's configuration
file and make it functional.


.SH OPTIONS
.IP -c
Check all configured feeds
.IP -C name
Check only the specified configured feed
.IP -u
Download only the latest episode from all configured feeds
.IP -U name
Download only the latest episode from the specified configured feed 

.SH BUGS
* As with tuxcast, bad things can happen to your configuration if your filesystem fills up while tuxcast-config is running
.SH AUTHOR
Tuxcast is written by David 'Cillian' Turner with occasional assistance from Roger 'Oojah' Light.

These manpages are by cypher_ of Linux User Group Radio (#lugradio) on the freenode network.
.SH "SEE ALSO"
.BR tuxcast (1),
