.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH tuxcast 1 "FEBRUARY 2008" 0.3 "tuxcast 0.3"
.SH NAME
tuxcast \- The Linux Podcast Client
.SH SYNOPSIS
.B tuxcast 
[\fIOPTION\fR]
.SH DESCRIPTION
Tuxcast is a minimal, portable podcatcher written in C++, with 
an interactive command line interface. 

Its configuration is performed by the included
.B tuxcast-config 
utility which must be
run to configure feeds and generate tuxcast's configuration
file to make it functional.


.SH OPTIONS
.TP 
\fB\-c\fR
Check all configured feeds
.TP 
\fB\-C name\fR
Check only the specified configured feed
.TP 
\fB\-u\fR
Download only the latest episode from all configured feeds
.TP 
\fB\-U name\fR
Download only the latest episode from the specified configured feed 
.TP
\fB\-f\fR
Forget about older downloaded podcasts
.TP
\fB\-v\fR
Show version, licensing and build configuration information
.TP
\fB\-h\fR
Show a help message

.SH BUGS
There are no known issues in this version of tuxcast.
.SH AUTHOR
Tuxcast is written by David 'Cillian' Turner assistance from Roger 'Oojah' Light, and Greatred.  Bittorrent support is based on the simple_client program for libtorrent, written by Jari 'Rakshasa' Sundell.

These manpages were written by cypher_ of Linux User Group Radio channel (#lugradio) on the freenode network.
.SH "SEE ALSO"
.BR tuxcast-config(1),
