include ../config.mk

install:
	$(INSTALL) -D -m 755 testpostrun.sh $(DESTDIR)$(PREFIX)/share/doc/$(APPNAME)/examples/hooks/testpostrun.sh
	$(INSTALL) -D -m 755 testpostdownload.sh $(DESTDIR)$(PREFIX)/share/doc/$(APPNAME)/examples/hooks/testpostdownload.sh
