/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *notebook1;
  GtkWidget *vbox1;
  GtkWidget *hbox1;
  GtkWidget *checkentry;
  GtkWidget *check;
  GtkWidget *checkall;
  GtkWidget *scrolledwindow3;
  GtkWidget *checkoutput;
  GtkWidget *label1;
  GtkWidget *vbox2;
  GtkWidget *hbox2;
  GtkWidget *up2dateentry;
  GtkWidget *up2date;
  GtkWidget *up2dateall;
  GtkWidget *scrolledwindow2;
  GtkWidget *up2dateoutput;
  GtkWidget *label2;
  GtkWidget *label4;
  GtkWidget *label3;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("window1"));
  gtk_window_set_default_size (GTK_WINDOW (window1), 600, 400);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_container_add (GTK_CONTAINER (window1), notebook1);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (notebook1), vbox1);

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox1, FALSE, TRUE, 0);

  checkentry = gtk_entry_new ();
  gtk_widget_show (checkentry);
  gtk_box_pack_start (GTK_BOX (hbox1), checkentry, TRUE, TRUE, 0);
  gtk_entry_set_text (GTK_ENTRY (checkentry), _("Enter feed name here"));

  check = gtk_button_new_with_mnemonic (_("Check"));
  gtk_widget_show (check);
  gtk_box_pack_start (GTK_BOX (hbox1), check, FALSE, FALSE, 0);

  checkall = gtk_button_new_with_mnemonic (_("Check all"));
  gtk_widget_show (checkall);
  gtk_box_pack_start (GTK_BOX (hbox1), checkall, FALSE, FALSE, 0);

  scrolledwindow3 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow3);
  gtk_box_pack_start (GTK_BOX (vbox1), scrolledwindow3, TRUE, TRUE, 0);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow3), GTK_SHADOW_IN);

  checkoutput = gtk_text_view_new ();
  gtk_widget_show (checkoutput);
  gtk_container_add (GTK_CONTAINER (scrolledwindow3), checkoutput);

  label1 = gtk_label_new (_("Check"));
  gtk_widget_show (label1);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label1);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox2);
  gtk_container_add (GTK_CONTAINER (notebook1), vbox2);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox2);
  gtk_box_pack_start (GTK_BOX (vbox2), hbox2, FALSE, TRUE, 0);

  up2dateentry = gtk_entry_new ();
  gtk_widget_show (up2dateentry);
  gtk_box_pack_start (GTK_BOX (hbox2), up2dateentry, TRUE, TRUE, 0);

  up2date = gtk_button_new_with_mnemonic (_("Up2Date"));
  gtk_widget_show (up2date);
  gtk_box_pack_start (GTK_BOX (hbox2), up2date, FALSE, FALSE, 0);

  up2dateall = gtk_button_new_with_mnemonic (_("Up2DateAll"));
  gtk_widget_show (up2dateall);
  gtk_box_pack_start (GTK_BOX (hbox2), up2dateall, FALSE, FALSE, 0);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow2);
  gtk_box_pack_start (GTK_BOX (vbox2), scrolledwindow2, TRUE, TRUE, 0);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow2), GTK_SHADOW_IN);

  up2dateoutput = gtk_text_view_new ();
  gtk_widget_show (up2dateoutput);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), up2dateoutput);

  label2 = gtk_label_new (_("Up2date"));
  gtk_widget_show (label2);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label2);

  label4 = gtk_label_new (_("TODO"));
  gtk_widget_show (label4);
  gtk_container_add (GTK_CONTAINER (notebook1), label4);

  label3 = gtk_label_new (_("Configuration"));
  gtk_widget_show (label3);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label3);

  g_signal_connect ((gpointer) check, "clicked",
                    G_CALLBACK (on_check_clicked),
                    NULL);
  g_signal_connect ((gpointer) checkall, "clicked",
                    G_CALLBACK (on_checkall_clicked),
                    NULL);
  g_signal_connect ((gpointer) up2date, "clicked",
                    G_CALLBACK (on_up2date_clicked),
                    NULL);
  g_signal_connect ((gpointer) up2dateall, "clicked",
                    G_CALLBACK (on_up2dateall_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (window1, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (window1, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (window1, checkentry, "checkentry");
  GLADE_HOOKUP_OBJECT (window1, check, "check");
  GLADE_HOOKUP_OBJECT (window1, checkall, "checkall");
  GLADE_HOOKUP_OBJECT (window1, scrolledwindow3, "scrolledwindow3");
  GLADE_HOOKUP_OBJECT (window1, checkoutput, "checkoutput");
  GLADE_HOOKUP_OBJECT (window1, label1, "label1");
  GLADE_HOOKUP_OBJECT (window1, vbox2, "vbox2");
  GLADE_HOOKUP_OBJECT (window1, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (window1, up2dateentry, "up2dateentry");
  GLADE_HOOKUP_OBJECT (window1, up2date, "up2date");
  GLADE_HOOKUP_OBJECT (window1, up2dateall, "up2dateall");
  GLADE_HOOKUP_OBJECT (window1, scrolledwindow2, "scrolledwindow2");
  GLADE_HOOKUP_OBJECT (window1, up2dateoutput, "up2dateoutput");
  GLADE_HOOKUP_OBJECT (window1, label2, "label2");
  GLADE_HOOKUP_OBJECT (window1, label4, "label4");
  GLADE_HOOKUP_OBJECT (window1, label3, "label3");

  return window1;
}

