/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"


extern GtkTextBuffer *checkoutputtext;
extern GtkTextBuffer *up2dateoutputtext;


int
main (int argc, char *argv[])
{
  GtkWidget *window1;

  GtkWidget *checkoutput;
  GtkWidget *up2dateoutput;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

//  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  window1 = create_window1 ();
  gtk_widget_show (window1);

  checkoutputtext = gtk_text_buffer_new(NULL);
  up2dateoutputtext = gtk_text_buffer_new(NULL);

  checkoutput = lookup_widget(window1, "checkoutput");
  up2dateoutput = lookup_widget(window1, "up2dateoutput");
  
  gtk_text_view_set_buffer((GtkTextView *)checkoutput, checkoutputtext);
  gtk_text_view_set_buffer((GtkTextView *)up2dateoutput, up2dateoutputtext);
	  

  gtk_main ();
  return 0;
}

